"""Open lmw in its own themed terminal window: Ghostty (https://ghostty.org), or Windows Terminal.

`lmw` typed in any shell re-launches itself in a Ghostty window styled with the LMW theme
(the same colors as the website). Ghostty has official builds for macOS and Linux; on Windows,
a Ghostty build is used if one is installed, otherwise Windows Terminal with the same theme.

Stay in the current window with `lmw --here`, or set "terminal": "none" in the config.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import List, Optional

from . import ui

REPO = Path(__file__).resolve().parent.parent

# LMW theme (matches the website): warm dark gray, orange accent.
BG, FG, ACCENT, SEL = "#1c1b19", "#ecebe6", "#d97a4a", "#3d3c38"
PALETTE = ["#2a2926", "#e07a6f", "#7fbf7f", "#e3b45f", "#7aa2d9", "#d97a4a", "#6fc2c2", "#c9c8c2",
           "#5c5b56", "#f0958b", "#9fd49f", "#f0c77a", "#9bbbe6", "#e8956a", "#8fd6d6", "#ecebe6"]


def lmw_home() -> Path:
    return Path(os.environ.get("LMW_HOME") or (Path.home() / ".lmw"))


# ------------------------------------------------------------------- Ghostty

def ghostty_config() -> Path:
    path = lmw_home() / "ghostty.conf"
    lines = [
        "# LMW theme for Ghostty (generated by lmw; edit freely)",
        "title = LMW",
        "background = " + BG.lstrip("#"),
        "foreground = " + FG.lstrip("#"),
        "cursor-color = " + ACCENT.lstrip("#"),
        "cursor-style = bar",
        "selection-background = " + SEL.lstrip("#"),
        "selection-foreground = " + FG.lstrip("#"),
    ] + ["palette = %d=%s" % (i, c) for i, c in enumerate(PALETTE)] + [
        "font-size = 14",
        "window-padding-x = 16",
        "window-padding-y = 12",
        "window-width = 112",
        "window-height = 36",
        "confirm-close-surface = false",
        "shell-integration = detect",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"
    if not path.is_file():  # never overwrite the user's edits
        path.write_text(text, encoding="utf-8")
    return path


def find_ghostty() -> Optional[List[str]]:
    """Command prefix that opens a new Ghostty window, or None."""
    if sys.platform == "darwin":
        for app in ("/Applications/Ghostty.app", str(Path.home() / "Applications/Ghostty.app")):
            if Path(app).is_dir():
                return ["open", "-na", app, "--args"]
        return None
    exe = shutil.which("ghostty")
    if exe:
        return [exe]
    if os.name == "nt":  # experimental / community Windows builds
        for c in (Path(os.environ.get("LOCALAPPDATA", "")) / "Programs" / "Ghostty" / "ghostty.exe",
                  Path(os.environ.get("ProgramFiles", "C:/Program Files")) / "Ghostty" / "ghostty.exe"):
            if c.is_file():
                return [str(c)]
    return None


# ----------------------------------------------------------- Windows Terminal

def windows_terminal_fragment() -> None:
    """Register the LMW color scheme + profile with Windows Terminal (JSON fragment)."""
    base = Path(os.environ.get("LOCALAPPDATA", "")) / "Microsoft" / "Windows Terminal" / "Fragments" / "LMW"
    names = ["black", "red", "green", "yellow", "blue", "purple", "cyan", "white"]
    scheme = {"name": "LMW", "background": BG, "foreground": FG, "cursorColor": ACCENT,
              "selectionBackground": SEL}
    for i, n in enumerate(names):
        scheme[n] = PALETTE[i]
        scheme["bright" + n.capitalize()] = PALETTE[i + 8]
    frag = {"schemes": [scheme], "profiles": [{
        "name": "LMW", "commandline": " ".join(_quote_win(x) for x in launch_command([])),
        "colorScheme": "LMW", "tabColor": ACCENT, "padding": "16, 12",
        "font": {"face": "Cascadia Mono", "size": 12}, "hidden": False}]}
    try:
        base.mkdir(parents=True, exist_ok=True)
        (base / "lmw.json").write_text(json.dumps(frag, indent=2), encoding="utf-8")
    except OSError:
        pass


def _quote_win(s: str) -> str:
    return '"%s"' % s if (" " in s or not s) else s


# ------------------------------------------------------------------- launch

def launch_command(args: List[str]) -> List[str]:
    """How the new window runs lmw: same Python, this checkout, and --here (no relaunch loop)."""
    runner = lmw_home() / "run-lmw.py"
    runner.parent.mkdir(parents=True, exist_ok=True)
    code = ("import sys\nsys.path.insert(0, %r)\nfrom lmw.cli import main\nsys.exit(main(sys.argv[1:]))\n" % str(REPO))
    if not runner.is_file() or runner.read_text(encoding="utf-8") != code:
        runner.write_text(code, encoding="utf-8")
    return [sys.executable, str(runner), "--here"] + list(args)


def should_relaunch(preference: str) -> bool:
    if preference == "none" or os.environ.get("LMW_HERE"):
        return False
    if not (sys.stdin.isatty() and sys.stdout.isatty()):
        return False  # scripts, pipes, CI
    if os.environ.get("TERM_PROGRAM", "").lower() == "ghostty" or os.environ.get("GHOSTTY_RESOURCES_DIR"):
        return False  # already in Ghostty
    if os.environ.get("SSH_CONNECTION") or os.environ.get("SSH_TTY"):
        return False  # remote shell: no GUI to open
    if sys.platform.startswith("linux") and not (os.environ.get("DISPLAY") or os.environ.get("WAYLAND_DISPLAY")):
        return False
    return True


def relaunch(args: List[str], preference: str = "auto") -> bool:
    """Open lmw in a Ghostty (or Windows Terminal) window. True if a new window was started."""
    if not should_relaunch(preference):
        return False
    cwd = os.getcwd()
    cmd = launch_command(args)
    ghostty = find_ghostty() if preference in ("auto", "ghostty") else None
    try:
        if ghostty:
            conf = ghostty_config()
            full = ghostty + ["--config-file=%s" % conf, "--working-directory=%s" % cwd, "-e"] + cmd
            _spawn(full)
            ui.ok("LMW 를 Ghostty 창에서 열었습니다   (이 창에서 쓰려면: lmw --here)")
            return True
        if os.name == "nt" and preference in ("auto", "wt") and shutil.which("wt"):
            windows_terminal_fragment()
            full = ["wt", "-w", "new", "new-tab", "--title", "LMW", "--tabColor", ACCENT,
                    "--colorScheme", "LMW", "-d", cwd] + [a.replace(";", "\\;") for a in cmd]
            _spawn(full)
            ui.ok("LMW 를 새 터미널 창에서 열었습니다   (이 창에서 쓰려면: lmw --here)")
            if preference == "auto":
                ui.info(ui.dim("Ghostty 를 쓰려면 Ghostty 를 설치하세요: https://ghostty.org"))
            return True
    except OSError as e:
        ui.warn("터미널 창을 열지 못해 여기서 실행합니다: %s" % e)
    if preference == "ghostty":
        ui.warn("Ghostty 를 찾지 못했습니다 — https://ghostty.org 에서 설치하세요 (여기서 실행합니다)")
    return False


def _spawn(cmd: List[str]) -> None:
    kw = {"stdin": subprocess.DEVNULL, "stdout": subprocess.DEVNULL, "stderr": subprocess.DEVNULL}
    if os.name == "nt":
        kw["creationflags"] = 0x00000008 | 0x00000200  # DETACHED_PROCESS | CREATE_NEW_PROCESS_GROUP
    else:
        kw["start_new_session"] = True
    subprocess.Popen(cmd, **kw)
